// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

[Table("Drink")]
public partial class Drink
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public int? AlcoholicPartId { get; set; }
    public int? AlcoholicPartAmount { get; set; }
    public int? NonAlcoholicPartId { get; set; }
    public int? NonAlcoholicPartAmount { get; set; }

    [ForeignKey("AlcoholicPartId")]
    [InverseProperty("DrinkAlcoholicParts")]
    public virtual Ingredient AlcoholicPart { get; set; }
    [ForeignKey("NonAlcoholicPartId")]
    [InverseProperty("DrinkNonAlcoholicParts")]
    public virtual Ingredient NonAlcoholicPart { get; set; }
}