// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

[Table("Ingredient")]
public partial class Ingredient
{
    public Ingredient()
    {
        DrinkAlcoholicParts = new HashSet<Drink>();
        DrinkNonAlcoholicParts = new HashSet<Drink>();
    }

    [Key]
    public int Id { get; set; }
    [Required]
    [StringLength(50)]
    public string Name { get; set; }
    public int PricePerCl { get; set; }
    public double AlcoholPercent { get; set; }

    [InverseProperty("AlcoholicPart")]
    public virtual ICollection<Drink> DrinkAlcoholicParts { get; set; }
    [InverseProperty("NonAlcoholicPart")]
    public virtual ICollection<Drink> DrinkNonAlcoholicParts { get; set; }
}