// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

[Table("CocktailIngredient")]
public partial class CocktailIngredient
{
    [Key]
    public int Id { get; set; }

    public int CocktailId { get; set; }
    public int IngredientId { get; set; }
    public int AmountInCl { get; set; }

    [ForeignKey("CocktailId")]
    [InverseProperty("CocktailIngredients")]
    public virtual Cocktail Cocktail { get; set; }
    [ForeignKey("IngredientId")]
    [InverseProperty("CocktailIngredients")]
    public virtual Ingredient Ingredient { get; set; }
}